POST http://localhost:8081/create HTTP/1.1
Content-Type: application/json

[
    {
        "name":"washing dishes",
        "checked":false
    },
    
    {
        "name":"Graceries",
        "checked":false
    },
    
    {
        "name":"Bathing kids",
        "checked":false
    }
    
]

###
PUT  http://localhost:8081/update HTTP/1.1
Content-Type: application/json

[
    {
        "checked":false},
        {
        "name":"Graceries"
    }
    
]

###

GET http://localhost:8081/list HTTP/1.1

Content-Type: application/json

###

DELETE  http://localhost:8081/delete HTTP/1.1
Content-Type: application/json

{
    "checked":false
}

###